### ISSUE TITLE
Unknown command `BF.RESERVE`

### ISSUE THREAD

**Issue by henrikstroem** [RedisBloom/redisbloom-py#18]
I am getting the error:

```text
redis.exceptions.ResponseError: unknown command `BF.RESERVE`, with args beginning with: `bloom`, `0.01`, `1000`,
```

This happens when running the `#Using Bloom Filter` example from the documentation - I get the same error with other scripts as well.

Redis Server is up and receives the request:
```text
57121:M 12 Sep 2020 11:08:12.964 - Accepted ::1:53467
57121:M 12 Sep 2020 11:08:12.970 - Client closed connection
```

Full stack trace:
```text
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    rb.bfCreate('bloom', 0.01, 1000)
  File "/Users/henrik/tmp/bloom/venv/lib/python3.7/site-packages/redisbloom/client.py", line 242, in bfCreate
    return self.execute_command(self.BF_RESERVE, *params)
  File "/Users/henrik/tmp/bloom/venv/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/Users/henrik/tmp/bloom/venv/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/henrik/tmp/bloom/venv/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: unknown command `BF.RESERVE`, with args beginning with: `bloom`, `0.01`, `1000`,
```

pip freeze:
```text
hiredis==1.1.0
redis==3.5.3
redisbloom==0.4.0
rmtest==0.7.0
six==1.15.0
```

Python 3.7.3.

**Comment by ashtul** [comment]
@henrikstroem 
Is the RedisBloom module loaded to the server? Can you try and enter the command in redis-cli?

**Comment by henrikstroem** [comment]
@gkorland Your comment made me try the docker image with redis-redisbloom, and that worked well. Rebuilding me Redis server solved the problem. Thank you.
